name: test
on: [push]
jobs:
  exec-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create .dev.env file
        working-directory: .
        run: |
          echo "${{ secrets.TRELLO_KEY }}" >> .dev.env
          echo "${{ secrets.TRELLO_TOKEN }}" >> .dev.env
          echo "${{ secrets.LIST_ID }}" >> .dev.env
          echo "${{ secrets.BUG_REPORT }}" >> .dev.env
          echo "${{ secrets.FEATURE_REQUEST }}" >> .dev.env
          echo "${{ secrets.CONTACT }}" >> .dev.env
          echo "${{ secrets.OTHER }}" >> .dev.env
      - name: start container
        working-directory: .devcontainer
        run: docker-compose up -d
      - name: setup test
        working-directory: .devcontainer
        run: docker-compose exec -T node bash -c "yarn && yarn proto"
      - name: run test
        working-directory: .devcontainer
        run: docker-compose exec -T node bash -c "yarn test"
